/**
 * Reason codes explain *why* a session received its score.
 *
 * They are written to the server-side decision record only. They are never sent
 * to the browser, so automated clients get no feedback to tune against.
 *
 * - `lean`: which way the reason pushes the score.
 * - `group`: where the evidence came from.
 */
export type ReasonLean = 'bot' | 'human' | 'neutral';
export type ReasonGroup = 'gate' | 'environment' | 'network' | 'behaviour' | 'engine';

export interface ReasonInfo {
  readonly group: ReasonGroup;
  readonly lean: ReasonLean;
  readonly description: string;
}

export const REASONS = {
  // Gates: decisive on their own. The session is scored as a bot without further analysis.
  honeypot_filled: {
    group: 'gate',
    lean: 'bot',
    description: 'A hidden honeypot form field was filled in.',
  },
  honeypot_trap_followed: {
    group: 'gate',
    lean: 'bot',
    description: 'An invisible trap link was followed.',
  },
  agent_canary_followed: {
    group: 'gate',
    lean: 'bot',
    description: 'Hidden instructions aimed at AI agents were acted on.',
  },
  nonce_invalid: {
    group: 'gate',
    lean: 'bot',
    description: 'The session nonce was missing, malformed or had a bad signature.',
  },
  nonce_expired: {
    group: 'gate',
    lean: 'bot',
    description: 'The session nonce was older than its allowed lifetime.',
  },
  nonce_replayed: {
    group: 'gate',
    lean: 'bot',
    description:
      'The nonce was presented from a different TLS client or browser than it was issued to.',
  },
  too_fast: {
    group: 'gate',
    lean: 'bot',
    description:
      'The client reported more elapsed time than had really passed since the nonce was issued, a sign of a fast-forwarded clock.',
  },
  ja4_non_browser: {
    group: 'gate',
    lean: 'bot',
    description:
      'The TLS fingerprint belongs to a non-browser HTTP library while the user agent claims to be a browser.',
  },
  automation_markers: {
    group: 'gate',
    lean: 'bot',
    description: 'Globals or properties left behind by an automation framework were found.',
  },

  // Environment: what the browser says about itself, and whether that story is consistent.
  webdriver: {
    group: 'environment',
    lean: 'bot',
    description: 'navigator.webdriver is true.',
  },
  headless_markers: {
    group: 'environment',
    lean: 'bot',
    description: 'Traits typical of a headless browser were found.',
  },
  software_renderer: {
    group: 'environment',
    lean: 'bot',
    description:
      'Graphics are rendered in software, which is typical of servers and headless browsers.',
  },
  ua_client_hints_mismatch: {
    group: 'environment',
    lean: 'bot',
    description: 'The user-agent string disagrees with the browser’s User-Agent Client Hints.',
  },
  worker_mismatch: {
    group: 'environment',
    lean: 'bot',
    description: 'Browser properties differ between the page and a Web Worker, a sign of spoofing.',
  },
  feature_mismatch: {
    group: 'environment',
    lean: 'bot',
    description: 'The browser lacks features its claimed version should have.',
  },
  native_tamper: {
    group: 'environment',
    lean: 'bot',
    description: 'Built-in browser functions have been overwritten.',
  },
  privacy_browser: {
    group: 'environment',
    lean: 'neutral',
    description:
      'A privacy-hardened browser was detected. Consistency penalties are switched off for this session.',
  },

  // Network: evidence from the TLS connection and HTTP headers, read at the edge.
  ua_ja4_mismatch: {
    group: 'network',
    lean: 'bot',
    description: 'The TLS fingerprint does not match the browser family in the user agent.',
  },
  sec_fetch_missing: {
    group: 'network',
    lean: 'bot',
    description:
      'Fetch metadata headers (Sec-Fetch-*) that this browser always sends were missing.',
  },
  timezone_mismatch: {
    group: 'network',
    lean: 'bot',
    description:
      'The browser’s time zone differs from the time zone of its IP address. VPN users also trigger this, so it is weighted lightly.',
  },
  verified_agent_signature: {
    group: 'network',
    lean: 'neutral',
    description: 'The request carried a valid Web Bot Auth signature from a declared agent.',
  },

  // Behaviour: how the person (or program) interacted with the page.
  synthetic_events: {
    group: 'behaviour',
    lean: 'bot',
    description: 'Input events were generated by script (isTrusted was false).',
  },
  pointer_linear: {
    group: 'behaviour',
    lean: 'bot',
    description: 'Pointer movement followed unnaturally straight lines at constant speed.',
  },
  pointer_teleport: {
    group: 'behaviour',
    lean: 'bot',
    description: 'Clicks happened with no pointer movement leading up to them.',
  },
  click_dead_center: {
    group: 'behaviour',
    lean: 'bot',
    description: 'Clicks landed exactly in the centre of their targets.',
  },
  keyboard_uniform: {
    group: 'behaviour',
    lean: 'bot',
    description: 'Key presses were evenly spaced, as a script would type.',
  },
  pointer_natural: {
    group: 'behaviour',
    lean: 'human',
    description: 'Pointer movement had natural curvature, speed changes and pauses.',
  },
  keyboard_natural: {
    group: 'behaviour',
    lean: 'human',
    description: 'Typing rhythm varied in the way human typing does.',
  },
  touch_natural: {
    group: 'behaviour',
    lean: 'human',
    description: 'Touch contact size, pressure and timing varied naturally.',
  },
  scroll_natural: {
    group: 'behaviour',
    lean: 'human',
    description: 'Scrolling showed natural acceleration and rhythm.',
  },
  no_interaction: {
    group: 'behaviour',
    lean: 'neutral',
    description:
      'No interaction yet. This lowers confidence but does not lower the score on its own.',
  },

  // Engine: how the decision was produced.
  no_js: {
    group: 'engine',
    lean: 'neutral',
    description: 'The client never ran the browser SDK. Only network evidence was available.',
  },
  jev_decision: {
    group: 'engine',
    lean: 'neutral',
    description: 'The score was produced by the Jev engine.',
  },
  jev_unavailable: {
    group: 'engine',
    lean: 'neutral',
    description:
      'The Jev engine timed out or returned an error, so the algorithmic engine scored this session.',
  },
} as const satisfies Record<string, ReasonInfo>;

export type ReasonCode = keyof typeof REASONS;

export const REASON_CODES: readonly ReasonCode[] = Object.keys(REASONS) as ReasonCode[];
