// Writes src/version.ts from the package.json in the current directory, so each
// package can report its own version at runtime without importing JSON.
import { readFileSync, writeFileSync } from 'node:fs';

const { version } = JSON.parse(readFileSync('package.json', 'utf8'));
const file = `// Generated by scripts/write-version.mjs. Do not edit.\nexport const VERSION = '${version}';\n`;
const path = 'src/version.ts';
let current = '';
try {
  current = readFileSync(path, 'utf8');
} catch {}
if (current !== file) writeFileSync(path, file);
